# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "SellSmooth"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "simple"

template: "template_toolkit"
engines:
  template:
    template_toolkit:
      start_tag: '[%'
      end_tag:   '%]'

plugins:
    Ajax:
        content_type: 'application/json'
    DBIC:
      default:
        dsn: dbi:Pg:dbname=smooth;host=127.0.0.1
        schema_class: SellSmooth::Base::Db::Pg
        user: smooth
        password: smooth
        options:
          pg_enable_utf8: 1
          RaiseError: 1
          PrintError: 1
    Localization:
      path: resources
      supported:
          - de_de
          - en_us
      default: en_us